# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Blog',
                'doc_host': 'https://BaileyAndrew.github.io',
                'git_url': 'https://github.com/BaileyAndrew/Blog',
                'lib_path': 'Blog'},
  'syms': {'Blog.core': {'Blog.core.foo': ('core.html#foo', 'Blog/core.py')}}}
